wandb:
  project: POLAR-background-prediction
  mode: online

wandb_watch: True  # log in w&b model & criterion

common:
  seed: 42
  n_epochs: 200
  device: cuda

dataset:
  filename: data/fmrate_dataset.csv
  feature_names:
    - unix_time
    - fe_cosmic
  target_names:
    - rate[0]
  train:
    size: 0.6
    batch_size: 200  # similar to sklearn 'auto'
    shuffle: True
  val:
    size: 0.2
    batch_size: 200
  test:
    size: 0.2
    batch_size: 200

optimizer:
  hyperparams:
    # For adam optimizer
    lr: 1e-3
    betas:
      - 0.9
      - 0.999
    eps: 1e-08
