wandb_version: 1

memory:
  desc: null
  value: null
steps:
  desc: null
  value:
  - - standardscaler
    - StandardScaler()
  - - mlpregressor
    - MLPRegressor(hidden_layer_sizes=[100, 100], max_iter=500, random_state=42)
verbose:
  desc: null
  value: false
standardscaler:
  desc: null
  value: StandardScaler()
mlpregressor:
  desc: null
  value: MLPRegressor(hidden_layer_sizes=[100, 100], max_iter=500, random_state=42)
standardscaler__copy:
  desc: null
  value: true
standardscaler__with_mean:
  desc: null
  value: true
standardscaler__with_std:
  desc: null
  value: true
mlpregressor__activation:
  desc: null
  value: relu
mlpregressor__alpha:
  desc: null
  value: 0.0001
mlpregressor__batch_size:
  desc: null
  value: auto
mlpregressor__beta_1:
  desc: null
  value: 0.9
mlpregressor__beta_2:
  desc: null
  value: 0.999
mlpregressor__early_stopping:
  desc: null
  value: false
mlpregressor__epsilon:
  desc: null
  value: 1.0e-08
mlpregressor__hidden_layer_sizes:
  desc: null
  value:
  - 100
  - 100
mlpregressor__learning_rate:
  desc: null
  value: constant
mlpregressor__learning_rate_init:
  desc: null
  value: 0.001
mlpregressor__max_fun:
  desc: null
  value: 15000
mlpregressor__max_iter:
  desc: null
  value: 500
mlpregressor__momentum:
  desc: null
  value: 0.9
mlpregressor__n_iter_no_change:
  desc: null
  value: 10
mlpregressor__nesterovs_momentum:
  desc: null
  value: true
mlpregressor__power_t:
  desc: null
  value: 0.5
mlpregressor__random_state:
  desc: null
  value: 42
mlpregressor__shuffle:
  desc: null
  value: true
mlpregressor__solver:
  desc: null
  value: adam
mlpregressor__tol:
  desc: null
  value: 0.0001
mlpregressor__validation_fraction:
  desc: null
  value: 0.1
mlpregressor__verbose:
  desc: null
  value: false
mlpregressor__warm_start:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.5
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1689276455.983222
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.15.5
      8:
      - 1
      - 3
      - 5
val_size:
  desc: null
  value: 0.2
test_size:
  desc: null
  value: 0.2
val_len:
  desc: null
  value: 12937
test_len:
  desc: null
  value: 12937
train_len:
  desc: null
  value: 38808
random_state:
  desc: null
  value: 42
shuffle_data:
  desc: null
  value: true
